install:
- npm install
- npm run test

script:
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_60dc46b2ca78_key -iv $encrypted_60dc46b2ca78_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -rv -e 'ssh -i id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' $TRAVIS_BUILD_DIR/build/* byteshark.be@ssh.byteshark.be:/www/chinees-poepen
  on:
    branch: master
